### ISSUE TITLE
CANAPE example projects ?

### ISSUE THREAD

**Issue by Aza1337** [ctxis/canape#4]
Hi !
I'm looking for project examples such as the one used for Citrix ICA (Black Hat 2012).
I've already tested the ones provided during your workshop at 44CON, but i'm still stuck with some features of Canape.
Thanks a lot

**Comment by nv1t** [comment]
Hi Aza1337

i know it is quite late. But there are not a lot of information around for Canape. Hopefully we can provide some explanation in the future, but at the moment, @mogwailabs has a really good canape workshop on github with a few features about Parser/Fuzzer and Basic Usage. (https://github.com/mogwailabs/canape-workshop2018)

There are still tons of stuff missing, but this will work for at least 90% for the stuff everybody uses canape for :)

Maybe this will help out.
